export const f2lCases = [
    // --- BASIC INSERTS (1-4) ---
    { id: 1, cat: 'Basic Inserts', opt: "U R U' R'", alts: ["y L' U' L"] },
    { id: 2, cat: 'Basic Inserts', opt: "y' U' R' U R", alts: ["F R' F' R"] },
    { id: 3, cat: 'Basic Inserts', opt: "y' R' U' R", alts: ["F' U F"] },
    { id: 4, cat: 'Basic Inserts', opt: "R U R'", alts: ["y L U L'"] },

    // --- DISCONNECTED PAIRS (5-10) ---
    { id: 5, cat: 'Disconnected Pairs', opt: "U' R U R' U2 R U' R'", alts: ["y' U2 R' U' R U' R' U R"] },
    { id: 6, cat: 'Disconnected Pairs', opt: "d R' U' R U2 R' U R", alts: ["y' U R' U' R U2 R' U R"] },
    { id: 7, cat: 'Disconnected Pairs', opt: "U' R U2 R' U2 R U' R'", alts: ["U' R U2 R' U R' F R F'"] },
    { id: 8, cat: 'Disconnected Pairs', opt: "d R' U2 R U2 R' U R", alts: ["y' U R' U2 R U2 R' U R"] },
    { id: 9, cat: 'Disconnected Pairs', opt: "U' R U' R' U F' U' F", alts: ["U' R U' R' d R' U' R"] },
    { id: 10, cat: 'Disconnected Pairs', opt: "U' R U R' U R U R'", alts: ["d R' U R d' R U R'"] },

    // --- CONNECTED PAIRS (11-18) ---
    { id: 11, cat: 'Connected Pairs', opt: "U' R U2 R' d R' U' R", alts: ["U' R U2 R' U F' U' F"] },
    { id: 12, cat: 'Connected Pairs', opt: "R U' R' U R U' R' U2 R U' R'", alts: ["R' U2 R2 U R2 U R"] },
    { id: 13, cat: 'Connected Pairs', opt: "y' U R' U R U' R' U' R", alts: ["d R' U R U' R' U' R"] },
    { id: 14, cat: 'Connected Pairs', opt: "U' R U' R' U R U R'", alts: ["U2 R2 U R' U R U2 R2"] },
    { id: 15, cat: 'Connected Pairs', opt: "R U R' U2 R U' R' U R U' R'", alts: ["R' D' R U' R' D R U R U' R'"] },
    { id: 16, cat: 'Connected Pairs', opt: "R U' R' U2 y' R' U' R", alts: ["R U' R' U2 F' U' F"] },
    { id: 17, cat: 'Connected Pairs', opt: "R U2 R' U' R U R'", alts: ["R U R' U' R U2 R' U2 R U R'"] },
    { id: 18, cat: 'Connected Pairs', opt: "y' R' U2 R U R' U' R", alts: ["y L' U2 L U L' U' L"] },

    // --- DISCONNECTED PAIRS (19-22) ---
    { id: 19, cat: 'Disconnected Pairs', opt: "U R U2 R' U R U' R'", alts: ["R U' R' U R U' R' U R U R'"] },
    { id: 20, cat: 'Disconnected Pairs', opt: "y' U' R' U2 R U' R' U R", alts: ["U' R U R' U r U' r' U2 r U r'"] },
    { id: 21, cat: 'Disconnected Pairs', opt: "R U' R' U2 R U R'", alts: ["U2 R' U' R S R f' U' F"] },
    { id: 22, cat: 'Disconnected Pairs', opt: "y' R' U R U2 R' U' R", alts: ["r U' r' U2 r U r'"] },

    // --- CONNECTED PAIRS (23-24) ---
    { id: 23, cat: 'Connected Pairs', opt: "R U' R' U' R U R' U2 R U R'", alts: ["U2 R2 U2 R' U' R U' R2"] },

    // --- CORNER IN SLOT (25-30) ---
    { id: 24, cat: 'Corner In Slot', opt: "U R U' R' d' L' U L", alts: ["F U R U' R' F' R U' R'"] },
    { id: 25, cat: 'Corner In Slot', opt: "U' R' F R F' R U R'", alts: ["R' U' R' U' R' U R U R"] },
    { id: 26, cat: 'Corner In Slot', opt: "U R U' R' F R' F' R", alts: ["R S' R' U R S R'"] },
    { id: 27, cat: 'Corner In Slot', opt: "R U' R' U R U' R'", alts: ["U2 R U' R' U R U' R'"] },
    { id: 28, cat: 'Corner In Slot', opt: "y' R' U R U' R' U R", alts: ["y L' U L U' L' U L"] },
    { id: 29, cat: 'Corner In Slot', opt: "y' R' U' R U R' U' R", alts: ["R' F R F' U R U' R'"] },
    { id: 30, cat: 'Corner In Slot', opt: "R U R' U' R U R'", alts: ["U2 R U R' U' R U R'"] },

    // --- EDGE IN SLOT (31-36) ---
    { id: 31, cat: 'Edge In Slot', opt: "U' R' F R F' R U' R'", alts: ["R U' R' U y' R' U R"] },
    { id: 32, cat: 'Edge In Slot', opt: "U R U' R' U R U' R' U R U' R'", alts: ["R U R' U' R U R' U' R U R'"] },
    { id: 33, cat: 'Edge In Slot', opt: "U' R U' R' U2 R U' R'", alts: ["R U R' U' R U' R' U R U' R'"] },
    { id: 34, cat: 'Edge In Slot', opt: "U R U R' U2 R U R'", alts: ["U' R U2 R' U R U R'"] },
    { id: 35, cat: 'Edge In Slot', opt: "U' R U R' U F' U' F", alts: ["U' R U R' d R' U' R"] },
    { id: 36, cat: 'Edge In Slot', opt: "U F' U' F U' R U R'", alts: ["U2 R' F R F' U2 R U R'"] },

    // --- PIECES IN SLOT (37-41) ---
    { id: 37, cat: 'Pieces In Slot', opt: "R U' R' U' R U R' U2 R U' R'", alts: ["R2 U2 F R2 F' U2 R' U R'"] },
    { id: 38, cat: 'Pieces In Slot', opt: "R U R' U' R U2 R' U' R U R'", alts: ["R U' R' d R' U' R U' R' U' R"] },
    { id: 39, cat: 'Pieces In Slot', opt: "R U2 R U R' U R U2 R2", alts: ["R U R' U2 R U' R' U R U R'"] },
    { id: 40, cat: 'Pieces In Slot', opt: "R U' R' U R U2 R' U R U' R'", alts: ["R U R' F U R U' R' F' U' R'"] },
    { id: 41, cat: 'Pieces In Slot', opt: "R U R' U' R U R' U' R U R'", alts: ["y' R' U' R U R' U' R U R' U' R"] }
];

export const ollCases = [
    { id: "1", cat: "No Edges Flipped", opt: "(R U2') (R2' F R F') U2' (R' F R F')" },
    { id: "2", cat: "No Edges Flipped", opt: "F (R U R' U') F' f (R U R' U') f'" },
    { id: "3", cat: "No Edges Flipped", opt: "f (R U R' U') f' U' F (R U R' U') F'" },
    { id: "4", cat: "No Edges Flipped", opt: "f (R U R' U') f' U F (R U R' U') F'" },
    { id: "5", cat: "Squares", opt: "r' U2' R U R' U r" },
    { id: "6", cat: "Squares", opt: "r U2 R' U' R U' r'" },
    { id: "7", cat: "Lightning Bolts", opt: "r U R' U R U2' r'" },
    { id: "8", cat: "Lightning Bolts", opt: "r' U' R U' R' U2 r" },
    { id: "9", cat: "Fish Shapes", opt: "(R U R' U') R' F (R2 U R' U') F'" },
    { id: "10", cat: "Fish Shapes", opt: "(R U R' U) (R' F R F') (R U2' R')" },
    { id: "11", cat: "Lightning Bolts", opt: "r' (R2 U R' U R U2 R') U M'" },
    { id: "12", cat: "Lightning Bolts", opt: "F (R U R' U') F' U F (R U R' U') F'" },
    { id: "13", cat: "Knight Move Shapes", opt: "(r U' r') (U' r U r') y' (R' U R)" },
    { id: "14", cat: "Knight Move Shapes", opt: "(R' F R) (U R' F' R) (F U' F')" },
    { id: "15", cat: "Knight Move Shapes", opt: "(r' U' r) (R' U' R U) (r' U r)" },
    { id: "16", cat: "Knight Move Shapes", opt: "(r U r') (R U R' U') (r U' r')" },
    { id: "17", cat: "No Edges Flipped", opt: "(R U R' U) (R' F R F') U2' (R' F R F')" },
    { id: "18", cat: "No Edges Flipped", opt: "y R U2' (R2' F R F') U2' M' (U R U' r')" },
    { id: "19", cat: "No Edges Flipped", opt: "M U (R U R' U') M' (R' F R F')" },
    { id: "20", cat: "No Edges Flipped", opt: "M U (R U R' U') M2' (U R U' r')" },
    { id: "21", cat: "All Edges Oriented", opt: "(R U2 R') (U' R U R') (U' R U' R')" },
    { id: "22", cat: "All Edges Oriented", opt: "R U2' R2' U' R2 U' R2' U2' R" },
    { id: "23", cat: "All Edges Oriented", opt: "R2 D (R' U2 R) D' (R' U2 R')" },
    { id: "24", cat: "All Edges Oriented", opt: "(r U R' U') (r' F R F')" },
    { id: "25", cat: "All Edges Oriented", opt: "F' (r U R' U') r' F R" },
    { id: "26", cat: "All Edges Oriented", opt: "R U2 R' U' R U' R'" },
    { id: "27", cat: "All Edges Oriented", opt: "R U R' U R U2' R'" },
    { id: "28", cat: "Corners Correct", opt: "(r U R' U') M (U R U' R')" },
    { id: "29", cat: "Awkward Shapes", opt: "y (R U R' U') (R U' R') (F' U' F) (R U R')" },
    { id: "30", cat: "Awkward Shapes", opt: "y' F U (R U2 R' U') (R U2 R' U') F'" },
    { id: "31", cat: "P-Shapes", opt: "(R' U' F) (U R U' R') F' R" },
    { id: "32", cat: "P-Shapes", opt: "S (R U R' U') (R' F R f)" },
    { id: "33", cat: "T-Shapes", opt: "(R U R' U') (R' F R F')" },
    { id: "34", cat: "C-Shapes", opt: "(R U R2' U') (R' F R U) R U' F'" },
    { id: "35", cat: "Fish Shapes", opt: "(R U2') (R2' F R F') (R U2' R')" },
    { id: "36", cat: "W-Shapes", opt: "(R' U' R U') (R' U R U) l U' R' U x" },
    { id: "37", cat: "Fish Shapes", opt: "F (R U' R' U') (R U R' F')" },
    { id: "38", cat: "W-Shapes", opt: "(R U R' U) (R U' R' U') (R' F R F')" },
    { id: "39", cat: "Lightning Bolts", opt: "L F' (L' U' L U) F U' L'" },
    { id: "40", cat: "Lightning Bolts", opt: "R' F (R U R' U') F' U R" },
    { id: "41", cat: "Awkward Shapes", opt: "(R U R' U R U2' R') F (R U R' U') F'" },
    { id: "42", cat: "Awkward Shapes", opt: "(R' U' R U' R' U2 R) F (R U R' U') F'" },
    { id: "43", cat: "P-Shapes", opt: "f (L' U' L U) f'" },
    { id: "44", cat: "P-Shapes", opt: "f (R U R' U') f'" },
    { id: "45", cat: "T-Shapes", opt: "F (R U R' U') F'" },
    { id: "46", cat: "C-Shapes", opt: "R' U' (R' F R F') U R" },
    { id: "47", cat: "L-Shapes", opt: "F' (L' U' L U) (L' U' L U) F" },
    { id: "48", cat: "L-Shapes", opt: "F (R U R' U') (R U R' U') F'" },
    { id: "49", cat: "L-Shapes", opt: "r U' r2 U r2 U r2' U' r" },
    { id: "50", cat: "L-Shapes", opt: "r' U r2 U' r2' U' r2 U r'" },
    { id: "51", cat: "I-Shapes", opt: "f (R U R' U') (R U R' U') f'" },
    { id: "52", cat: "I-Shapes", opt: "(R' U' R U' R' U) y' (R' U R) B" },
    { id: "53", cat: "L-Shapes", opt: "(r' U' R U') (R' U R U') R' U2 r" },
    { id: "54", cat: "L-Shapes", opt: "(r U R' U) (R U' R' U) R U2' r'" },
    { id: "55", cat: "I-Shapes", opt: "y (R' F R U) (R U' R2' F') R2 U' R' (U R U R')" },
    { id: "56", cat: "I-Shapes", opt: "r' U' r (U' R' U R) (U' R' U R) r' U r" },
    { id: "57", cat: "Corners Correct", opt: "(R U R' U') M' (U R U' r')" }
];

export const pllCases = [
    { id: "Ub", cat: "Edges Only", opt: "R2 U (R U R' U') R' U' (R' U R')" },
    { id: "Z", cat: "Edges Only", opt: "(M2' U M2' U) (M' U2) (M2' U2 M')" },
    { id: "Ua", cat: "Edges Only", opt: "(R U' R U) R U (R U' R' U') R2" },
    { id: "H", cat: "Edges Only", opt: "(M2' U M2') U2 (M2' U M2')" },
    { id: "Aa", cat: "Corners Only", opt: "x (R' U R') D2 (R U' R') D2 R2 x'" },
    { id: "E", cat: "Corners Only", opt: "x' (R U' R' D) (R U R' D') (R U R' D) (R U' R' D') x" },
    { id: "Ab", cat: "Corners Only", opt: "x R2' D2 (R U R') D2 (R U' R) x'" },
    { id: "Ra", cat: "Adjacent Corners", opt: "(R U' R' U') (R U R D) (R' U' R D') (R' U2 R')" },
    { id: "Ja", cat: "Adjacent Corners", opt: "(R' U L' U2) (R U' R' U2 R) L" },
    { id: "T", cat: "Adjacent Corners", opt: "(R U R' U') (R' F R2 U') R' U' (R U R' F')" },
    { id: "Rb", cat: "Adjacent Corners", opt: "(R' U2 R U2') R' F (R U R' U') R' F' R2" },
    { id: "Jb", cat: "Adjacent Corners", opt: "(R U R' F') (R U R' U') R' F R2 U' R'" },
    { id: "F", cat: "Adjacent Corners", opt: "(R' U' F') (R U R' U') (R' F R2 U') (R' U' R U) (R' U R)" },
    { id: "V", cat: "Diagonal Corners", opt: "(R' U R' U') y (R' F' R2 U') (R' U R' F) R F" },
    { id: "Na", cat: "Diagonal Corners", opt: "(R U R' U) (R U R' F') (R U R' U') (R' F R2 U') R' U2 (R U' R')" },
    { id: "Y", cat: "Diagonal Corners", opt: "F (R U' R' U') (R U R' F') (R U R' U') (R' F R F')" },
    { id: "Nb", cat: "Diagonal Corners", opt: "(R' U R U') (R' F' U' F) (R U R' F) R' F' (R U' R)" },
    { id: "Ga", cat: "G Perms (Double cycle)", opt: "R2 U (R' U R' U') (R U' R2) D U' (R' U R D')" },
    { id: "Gc", cat: "G Perms (Double cycle)", opt: "R2 U' (R U' R U) (R' U R2 D') (U R U' R') D" },
    { id: "Gb", cat: "G Perms (Double cycle)", opt: "(F' U' F) (R2 u R' U) (R U' R u') R2'" },
    { id: "Gd", cat: "G Perms (Double cycle)", opt: "D' (R U R' U') D (R2 U' R U') (R' U R' U) R2" },
];